"""
Django settings for nothing_brain_project project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ng#*cg_492&2h86n64k%*@o$1$62!v%iekdon_n84dc#o-p*-b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# DIPERBARUI: Mengambil host ngrok dari file .env
NGROK_HOSTNAME = '2b12-103-18-34-172.ngrok-free.app'
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.herokuapp.com', 'nothingbrain.store','.nothingbrain.store','.vercel.app','justifyingly-nontonic-shaunna.ngrok-free.dev']
if NGROK_HOSTNAME:
    ALLOWED_HOSTS.append(NGROK_HOSTNAME)

# BARU: Menambahkan origin ngrok ke daftar yang dipercaya untuk CSRF
CSRF_TRUSTED_ORIGINS = [
    "https://justifyingly-nontonic-shaunna.ngrok-free.dev",
]
if NGROK_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{NGROK_HOSTNAME}')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store.apps.StoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nothing_brain_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart',
                'store.context_processors.appwrite_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'nothing_brain_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'id-id'
TIME_ZONE = 'Asia/Jakarta'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# Konfigurasi file statis (CSS, JavaScript, Gambar)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Untuk deployment

# Konfigurasi file media (konten yang diunggah pengguna)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ID sesi untuk keranjang belanja
CART_SESSION_ID = 'cart'

# BARU: Konfigurasi Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'atheneservice@gmail.com'
EMAIL_HOST_PASSWORD = 'yswuzxhfjmtuclxh'
DEFAULT_ADMIN_EMAIL = 'atheneservice@gmail.com' # Email fallback

LOGIN_REDIRECT_URL = 'store:landing_page'
LOGOUT_REDIRECT_URL = 'store:landing_page'

# MIDTRANS_SERVER_KEY = config('MIDTRANS_SERVER_KEY')
# MIDTRANS_CLIENT_KEY = config('MIDTRANS_CLIENT_KEY')
MIDTRANS_CLIENT_KEY ='Mid-client-qqVgrIen_h4x17Rl'
MIDTRANS_SERVER_KEY ='Mid-server-Q1ON-GQuRJBWnYEm8yKB4qJW'
MIDTRANS_IS_PRODUCTION = True # Set ke True saat di server produksi

APPWRITE_PROJECT_ID='6850e68c003410e6c484'
APPWRITE_DATABASE_ID='main_db'
APPWRITE_PRODUCT_STOCK_COLLECTION_ID='product_stock'
APPWRITE_API_KEY='standard_875be58b849bae4e3e0ac85fe3e47d69f1bd93315849d9528dd7596a29d60818b41d2c517e9e3d1f9a39d8feccdcf5e9617fca6be76e077c68cb470c087408845682a11ecc7ff1489b4bb675d8ee598b2d9a7a067a4d5103fd7d1605729a53c2f7299234fa75f72d11676979305d8edc2b4beceba9a3d6bde7d6f58bf20c0734'
APPWRITE_MESSAGE_PROVIDER_ID='68690822001cce328d27'

RAJAONGKIR_API_KEY='JEReqpSS127c76f8c57e2c9da9I1AbX6'

RAJAONGKIR_ORIGIN_CITY_ID='175' 

