# Generated by Django 4.2.5 on 2025-07-02 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'kategori',
                'verbose_name_plural': 'kategori',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nama Depan')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nama Belakang')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=250, verbose_name='Alamat')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Kode Pos')),
                ('city', models.CharField(max_length=100, verbose_name='Kota')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('paid', models.BooleanField(default=False, verbose_name='Sudah Dibayar')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'pesanan',
                'verbose_name_plural': 'pesanan',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nama Produk')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Gambar')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Harga')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('available', models.BooleanField(default=True, verbose_name='Tersedia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'produk',
                'verbose_name_plural': 'produk',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Harga')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.product')),
            ],
            options={
                'verbose_name': 'item pesanan',
                'verbose_name_plural': 'item pesanan',
            },
        ),
    ]
