# Generated by Django 4.2.5 on 2025-07-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Contoh: Hitam, Putih, Merah', max_length=50, verbose_name='Warna')),
                ('size', models.CharField(help_text='Contoh: S, M, L, XL', max_length=10, verbose_name='Ukuran')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('image', models.ImageField(blank=True, help_text='Unggah gambar spesifik untuk varian warna ini.', null=True, upload_to='products/variants/', verbose_name='Gambar Varian')),
            ],
            options={
                'verbose_name': 'varian produk',
                'verbose_name_plural': 'varian produk',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Harga dasar produk. Harga bisa berbeda per varian.', max_digits=10, verbose_name='Harga Dasar'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'size')},
        ),
    ]
