# Generated by Django 4.2.5 on 2025-07-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productvariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Harga dasar produk.', max_digits=10, verbose_name='Harga Dasar'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(help_text='Contoh: Hitam, Putih, Merah', max_length=50, verbose_name='Nama Warna'),
        ),
    ]
