# Generated by Django 4.2.5 on 2025-07-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_productvariant_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='BEYOND THE NOISE', max_length=100, verbose_name='Judul Hero')),
                ('hero_subtitle', models.CharField(default='Gaya adalah pemberontakan. Temukan identitas Anda.', max_length=200, verbose_name='Subjudul Hero')),
                ('hero_image', models.ImageField(upload_to='landing_page/', verbose_name='Gambar Latar Hero')),
            ],
            options={
                'verbose_name': 'Konten Landing Page',
                'verbose_name_plural': 'Konten Landing Page',
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stok'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Harga'),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
