# Generated by Django 4.2.5 on 2025-07-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_stock_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Judul Koleksi')),
                ('image', models.ImageField(upload_to='featured_collections/', verbose_name='Gambar Koleksi')),
                ('link', models.CharField(help_text='Contoh: t-shirts, hoodies, aksesoris', max_length=200, verbose_name='Link (URL Slug Kategori)')),
            ],
            options={
                'verbose_name': 'Koleksi Pilihan',
                'verbose_name_plural': 'Koleksi Pilihan',
            },
        ),
        migrations.CreateModel(
            name='LookbookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lookbook/', verbose_name='Gambar Lookbook')),
                ('order', models.PositiveIntegerField(default=0, help_text='Gambar dengan urutan lebih kecil akan tampil lebih dulu.', verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Gambar Lookbook',
                'verbose_name_plural': 'Gambar Lookbook',
                'ordering': ['order'],
            },
        ),
    ]
