# Generated by Django 4.2.5 on 2025-07-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_featuredcollection_lookbookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcollection',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Kategori Terkait'),
        ),
    ]
