# Generated by Django 4.2.5 on 2025-07-03 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_alter_featuredcollection_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Foto Profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('address_line', models.CharField(max_length=250, verbose_name='Alamat')),
                ('city', models.CharField(max_length=100, verbose_name='Kota')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Kode Pos')),
                ('is_default', models.BooleanField(default=False, verbose_name='Jadikan Alamat Utama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alamat',
                'verbose_name_plural': 'Alamat',
            },
        ),
    ]
