# Generated by Django 4.2.5 on 2025-07-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TENTANG NOTHING_BRAIN', max_length=100, verbose_name='Judul Halaman')),
                ('subtitle', models.CharField(default='Kami bukan sekadar merek. Kami adalah sebuah ide.', max_length=200, verbose_name='Subjudul Halaman')),
                ('philosophy_title', models.CharField(default='FILOSOFI KAMI', max_length=100, verbose_name='Judul Filosofi')),
                ('philosophy_text', models.TextField(default='Isi teks filosofi di sini.', verbose_name='Teks Filosofi')),
                ('philosophy_image', models.ImageField(upload_to='about_us/', verbose_name='Gambar Filosofi')),
                ('community_title', models.CharField(default='BERGABUNG DENGAN KAMI', max_length=100, verbose_name='Judul Komunitas')),
                ('community_text', models.TextField(default='Isi teks komunitas di sini.', verbose_name='Teks Komunitas')),
            ],
            options={
                'verbose_name': 'Konten Halaman Tentang Kami',
                'verbose_name_plural': 'Konten Halaman Tentang Kami',
            },
        ),
    ]
