# Generated by Django 4.2.5 on 2025-07-05 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_order_paid_order_midtrans_snap_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode Kupon')),
                ('valid_from', models.DateTimeField(verbose_name='Berlaku Dari')),
                ('valid_to', models.DateTimeField(verbose_name='Berlaku Hingga')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Diskon (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kupon',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=15000, max_digits=10, verbose_name='Biaya Pengiriman'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_option',
            field=models.CharField(default='Jasa Kirim Toko', max_length=50, verbose_name='Opsi Pengiriman'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.coupon'),
        ),
    ]
