# Generated by Django 4.2.5 on 2025-07-06 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_coupon_order_discount_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
