# Generated by Django 6.0 on 2025-12-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_order_coupon_remove_order_discount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_id_2abda1_idx',
            old_fields=('id', 'slug'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Nama Lengakap'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_variant_per_product'),
        ),
    ]
