# Generated by Django 6.0 on 2026-01-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_offlinesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Isi jika harga berbeda dari produk utama. Kosongkan jika sama.', max_digits=10, null=True, verbose_name='Harga Varian'),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='lookbookimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Urutan kecil tampil duluan.', verbose_name='Urutan'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Harga Saat Beli'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Harga default produk.', max_digits=10, verbose_name='Harga Dasar'),
        ),
    ]
