# Generated by Django 6.0 on 2026-01-14 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_productvariant_price_alter_address_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlinesale',
            options={'verbose_name': 'Penjualan Manual/Offline', 'verbose_name_plural': 'Penjualan Manual/Offline'},
        ),
        migrations.AlterField(
            model_name='offlinesale',
            name='channel',
            field=models.CharField(choices=[('offline', 'Offline Store'), ('wa', 'WhatsApp'), ('ig', 'Instagram'), ('mp', 'Marketplace Lain')], max_length=50, verbose_name='Saluran Penjualan'),
        ),
        migrations.AlterField(
            model_name='offlinesale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Transaksi'),
        ),
        migrations.AlterField(
            model_name='offlinesale',
            name='note',
            field=models.TextField(blank=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='offlinesale',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Harga Total'),
        ),
        migrations.AlterField(
            model_name='offlinesale',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Jumlah Terjual'),
        ),
        migrations.AlterField(
            model_name='offlinesale',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin Pencatat'),
        ),
        migrations.AlterField(
            model_name='offlinesale',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productvariant', verbose_name='Produk Varian'),
        ),
    ]
