# Generated by Django 6.0.1 on 2026-01-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_offlinesale_options_alter_offlinesale_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('ALL', 'All Size'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10, verbose_name='Ukuran'),
        ),
    ]
