# Generated by Django 6.0 on 2026-01-14 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_productvariant_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlinesale',
            options={'verbose_name': 'Penjualan Manual/Offline (Lama)', 'verbose_name_plural': 'Penjualan Manual/Offline (Lama)'},
        ),
        migrations.AddField(
            model_name='order',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Kasir'),
        ),
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('online', 'Online Store'), ('pos', 'POS')], default='online', max_length=20, verbose_name='Channel'),
        ),
    ]
